#pragma once


// #define SET_WIFI_SSID "Your_SSID"
// #define SET_WIFI_PASSWORD "Your_PASSWORD"

// #define USE_FLOAT_FOR_DOUBLE 

// #define SHS_SET_SENSOR_AVERAGE_SAMPLES 20

// #define SHS_SET_DEFAULT_TCP_PORT 5000
// #define SHS_SET_DEFAULT_UDP_PORT 6000

// #define SHS_SET_DEFAULT_MULTICAST_IP "224.0.0.4"
// #define SHS_SET_DEFAULT_BROADCAST_IP "192.168.1.255"

// #define SHS_SET_GMT 0
