name: SHS core tests
on:
    push:

    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Set up CMake
              uses: lukka/get-cmake@latest

            - name: Run build-test for ShsCore
              run: |
                  cd src/SHScore
                  mkdir -p build
                  cd build
                  cmake -DSHS_CMF_QT=OFF -DSHS_CMF_UNUSE_SHS_SETTINGS=ON -DCMAKE_CXX_FLAGS="-Wall" ..
                  cmake --build .
            - name: Build and run ShsCore tests
              run: |
                  cd src/SHStests/ShsCoreTests
                  chmod +x build_shs_core_tests.sh
                  ./build_shs_core_tests.sh -r
