name: SHS core tests
on:
    push:

    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Set up CMake
              uses: lukka/get-cmake@v3

            - name: Build and run tests
              run: cd src/SHStests/ShsCoreTests
                  chmod +x build_shs_core_tests.sh
                  ./build_shs_core_tests.sh -r
